# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200403_0824'),
        ('comment', '0002_auto_20200407_2229'),
    ]

    operations = [
    ]
